[tool.black]
line-length = 100
target-version = ["py313"]
extend-exclude = '''
(
  ^\.venv/
  | ^\.devcontainer/
  | ^data/
  | ^\.github/
)
'''
[tool.pytest.ini_options]
addopts = "-q --cov=./ --cov-report=term-missing --cov-report=xml:coverage.xml"
